spring.application.name=prueba-tecnica
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/products_db
spring.datasource.username=keycloak
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000